# ---------------------------------
# Test comments
# Copyright (c) Ilia Tretiak 2020.
#
# ---------------------------------

name: CI
env:
  APP_ENV : "my application env variable"
  APP_NAME: "test-app:${{ github.sha }}"

on:
  push:
    branches: [master]

jobs:
  testing: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Print hello world
        run: echo "hello world - testing!"

      - name: Print any env variables
        run: |
          echo "APP_NAME: ${{ env.APP_NAME }}" 
          echo "APP_ENV: ${{ env.APP_ENV }}" 
      
      - name: Clone this repository
        uses: actions/checkout@v1
        
      - name: Print all files
        run: ll 
        
      - name: Check some packages
        run: |
          aws --version
          mvn --version
          zip
          

  deploy: 
    runs-on: ubuntu-latest
    needs: [testing]
    
    steps:
      - name: Print hello world
        run: echo "hello world - deploy!"

