# ---------------------------------
# Test comments
# Copyright (c) Ilia Tretiak 2020.
#
# ---------------------------------

name: CI/CD_pipeline_to_AWS
env:
  EB_APPLICATION_NAME       : "actions-test-app"
  EB_PACKAGE_S3_BUCKET_NAME : "github-actions-testing-packages-bucket"
  EB_ENVIRONMENT_NAME       : "ActionsTestApp-env"
  DEPLOY_PACKAGE_NAME       : "actions-test-app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-2"

on:
  push:
    branches: [master]

jobs:
  ci-pipeline: 
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.1
        with:
          java-version: '14'
      
      - name: Git clone this repository
        uses: actions/checkout@v1
         
      - name: Run application tests
        run:  mvn test

      - name: Create ZIP deployment package
        run:  zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id        : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key    : ${{ secrets.AWS_SECRET_KEY }}
          aws-region               : ${{ env.AWS_REGION_NAME }}

      - name: Copy ZIP deployment package to AWS S3 Bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - name: Print CI-pipeline finish message
        run: echo "CI-pipeline finished successfully !"  


  cd-pipeline:
    runs-on: ubuntu-latest
    needs: [ci-pipeline]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id        : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key    : ${{ secrets.AWS_SECRET_KEY }}
          aws-region               : ${{ env.AWS_REGION_NAME }}

      - name: Create new Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "version:${{ github.sha }}" \
          --description "commit-sha:${{ github.sha }}"

      - name: Deploy new Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
          --version-label "version:${{ github.sha }}"

      - name: Print CD-pipeline finish message
        run: echo "CD-pipeline finished successfully !" 
   
